#!/usr/bin/python

import rospy
from rosflight_msgs.msg import RCRaw
from rosflight_joystick_base import rosflight_joystick_base

class rosflight_joystic_RC(rosflight_joystick_base):
    def __init__(self, device = 0):
        rosflight_joystick_base.__init__(self, device)

        rospy.init_node('rc_joy')
        rc_pub = rospy.Publisher('RC', RCRaw, queue_size=10)

        while not rospy.is_shutdown():
            if self.update():
                msg = RCRaw()
                msg.header.stamp = rospy.Time.now()

                msg.values[0] = self.get_value('x')
                msg.values[1] = self.get_value('y')
                msg.values[2] = self.get_value('F')
                msg.values[3] = self.get_value('z')
                msg.values[4] = self.get_value('aux1')
                msg.values[5] = self.get_value('aux2')
                msg.values[6] = self.get_value('aux3')
                msg.values[7] = self.get_value('aux4')

                rc_pub.publish(msg)

    def get_value(self, key):
        return self.values[key] * 500 + 1500

if __name__ == "__main__":
    joy_object = rosflight_joystic_RC()
